
name: ClassClock
githubURL: https://github.com/MoralCode/ClassClock
slackURL: https://join.slack.com/t/classclock/shared_invite/enQtNTE0MDkyNzAwNzU3LWNhMGUwODU2ZjhkYTYxMTgzNDE1OWEyMGY2OGNiNTBhOWM5NDVhZGUzNDVlNzRiZTE3NTNmODFjYWNkNDhmMDU
twitterURL: https://twitter.com/classclockapp
instagramURL: https://www.instagram.com/classclockapp/